source ~/.vim/vundle.vim
source ~/.vim/base.vim
source ~/.vim/functions.vim
source ~/.vim/pliage.vim
source ~/.vim/shortcuts.vim
source ~/.vim/ultisnips.vim
source ~/.vim/nerdtree.vim
source ~/.vim/tagbar.vim
source ~/.vim/undotree.vim
source ~/.vim/indentline.vim
source ~/.vim/airline.vim
source ~/.vim/tmuxline.vim
source ~/.vim/VCS.vim
source ~/.vim/C++.vim
source ~/.vim/ale.vim
source ~/.vim/fzf.vim
source ~/.vim/ack.vim
source ~/.vim/deoplete.vim
source ~/.vim/bottom.vim
source ~/.vim/NERDCommenter.vim
